name = "wedding"
compatibility_date = "2026-06-07"
pages_build_output_dir = "dist"

# Keep this in sync with the staging D1 database Terraform output.
[[d1_databases]]
binding = "DB"
database_name = "thesharpes-wedding-staging-rsvps"
database_id = "56d9d51b-5588-4f65-80ec-d04768b00d64"
